---
- name: Ensure Pip is installed.
  become: true
  package:
    name: "python3-pip"
    state: present

- name: Ensure directory for application
  become: true
  file:
    owner: "{{ ansible_user_id }}"
    path: "{{ gateway_path }}"
    state: directory
    mode: 0755

- name: Install docker libraries
  become: true
  pip:
    name:
      - docker
      - docker-compose
    state: present

- name: Copy docker-compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ gateway_path }}/docker-compose.yml"
    mode: u=rw,g=r,o=r

- name: Copy env
  template:
    src: .env.j2
    dest: "{{ gateway_path }}/.env"
    mode: u=rw,g=r,o=r


- name: Run docker-compose
  become: true
  community.docker.docker_compose:
    pull: true
    recreate: always
    state: present
    project_src: "{{ gateway_path }}"